config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root "home#index"

  resources :posts, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :member
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_member!, except: [:index]

    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.member_id = current_member.id
        if @post.save
            redirect_to posts_path, notice: "post successfully created"
        else
            flash.now[:failure] = "somethign went wrong. post not created"
            render :new, status: :unprocessable_entity
        end
    end

    private

    def post_params
        params.require(:post).permit(:title, :text, :member_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


    <% flash.each do |name, msg| %>

    <div class="<%= name %>">
      <%= msg %>
    </div>
    <% end %>
    <%= link_to "Home", root_path %> |
    <%= link_to "All Posts", posts_path %> |
    <% if current_member %>
      <%= link_to "Logout", destroy_member_session_path, data: { turbo_method: :delete } %> 
    <% else %>
      <%= link_to "Login", new_member_session_path %> 
    <% end %>
    

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>posts index</h1>


<% @posts.each do |post| %>

<section class="<%= post.id %>">

    <h4><%= post.title %></h4>

    <% if current_member %>
        <p>by: <%= post.member.name %></p>
    <% end %>
    
    <p><%= post.text %></p>
</section>

<% end %>

app/views/posts/new.html.erb
<h1>new post</h1>

<%= form_with model: @post do |form| %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

     <div>
        <%= form.label :text %>
        <%= form.text_area :text %>
    </div>

     <div>
       <%= form.submit "Create Post" %>
    </div>
<% end %>